JAVAPATH: '/usr/bin/java'
GATKPATH: '/gatk/gatk.jar'
referencePath: '/home/yigewu2012/inputs/Homo_sapiens_assembly19.fasta'
exomeBedPath: '/home/yigewu2012/inputs/2.1M_Human_Exome.bed'
outputDIR: '/home/yigewu2012/outputs/2.1M_Human_Exome.bed/OV/'
normalBamPaths: '/home/yigewu2012/inputs/OV_normalBamPaths.list'
cancerBamPaths: '/home/yigewu2012/inputs/OV_tumorBamPaths.list'
