JAVAPATH: '/usr/bin/java'
GATKPATH: '/home/software/gatk-4.beta.5/gatk-package-4.beta.5-local.jar'
referencePath: '/diskmnt/Projects/CPTAC3CNV/gatk4wxscnv/inputs/Homo_sapiens_assembly19.fasta'
exomeBedPath: '/diskmnt/Projects/CPTAC3CNV/gatk4wxscnv/inputs/nexterarapidcapture_exome_targetedregions_v1.2.bed'
outputDIR: '/diskmnt/Projects/CPTAC3CNV/gatk4wxscnv/outputs/CPTAC3.CCRC.b5/CCRC/'
normalBamPaths: '/diskmnt/Projects/CPTAC3CNV/gatk4wxscnv/inputs/CPTAC3.CCRC.b5.BamMap.dat_WXS_blood_normal_CCRC.list'
cancerBamPaths: '/diskmnt/Projects/CPTAC3CNV/gatk4wxscnv/inputs/CPTAC3.CCRC.b5.BamMap.dat_WXS_tumor_CCRC.list'
